# Generated by Django 4.0.4 on 2022-05-04 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_buy_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
