# Generated by Django 4.0.4 on 2022-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advertisement_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
