# Generated by Django 4.0.4 on 2022-05-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_alter_advertisement_buyer_alter_advertisement_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
