# Generated by Django 4.0.4 on 2022-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_advertisement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='long_description',
            field=models.TextField(),
        ),
    ]
