# Generated by Django 4.0.4 on 2022-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_advertisement_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidson',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
