# Generated by Django 4.0.4 on 2022-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_bidson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidson',
            name='bid_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
