# Generated by Django 4.0.4 on 2022-05-08 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0010_alter_bidson_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidson',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidson', to='ads.advertisement'),
        ),
        migrations.AlterField(
            model_name='bidson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidson', to=settings.AUTH_USER_MODEL),
        ),
    ]
