# Generated by Django 4.0.4 on 2022-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_advertisement_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='reserve',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
