# Generated by Django 4.0.4 on 2022-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_advertisement_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidson',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
