# Generated by Django 4.0.4 on 2022-05-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='ads.condition'),
        ),
    ]
