# Generated by Django 4.0.4 on 2022-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
