# Generated by Django 4.0.4 on 2022-05-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_advertisement_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='condition1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ads.condition'),
        ),
    ]
