# Generated by Django 4.0.4 on 2022-05-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_remove_advertisement_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='condition1',
            new_name='condition',
        ),
    ]
