# Generated by Django 4.0.4 on 2022-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_advertisement_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
