# Generated by Django 4.0.4 on 2022-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_rename_condition1_advertisement_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='reserve',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
