# Generated by Django 4.0.4 on 2022-05-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('street_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('rating', models.FloatField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=9999)),
                ('ssn', models.CharField(blank=True, max_length=10)),
                ('bank', models.CharField(blank=True, max_length=10)),
                ('hb', models.CharField(blank=True, max_length=10)),
                ('account_no', models.CharField(blank=True, max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address')),
            ],
        ),
    ]
