# Generated by Django 4.0.4 on 2022-05-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
