# Generated by Django 4.0.4 on 2022-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_checkout_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='credid_card_fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
