# Generated by Django 4.0.4 on 2022-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_checkout_credid_card_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='credid_card_expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
