# Generated by Django 4.0.4 on 2022-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_checkout_credid_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='credid_card_number',
            field=models.CharField(max_length=16),
        ),
    ]
